/**
 * Google Sheets helpers for the Admin spreadsheet.
 *
 * MonthlySchedule is generated by the existing Calendar cache and may be cleared
 * and rebuilt at any time. Persistent student-number tag state therefore lives
 * in a separate CalendarStudentIDs tab.
 */
import { google } from 'googleapis';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirnameHere = dirname(fileURLToPath(import.meta.url));
const MONTHLY_SCHEDULE_SHEET = 'MonthlySchedule';
const MONTHLY_SCHEDULE_RANGE = `'${MONTHLY_SCHEDULE_SHEET}'!A:Z`;
const STUDENT_ID_SHEET = 'CalendarStudentIDs';
const STUDENT_ID_HEADERS = ['EventID', 'Date', 'StudentName', 'StudentID', 'UpdatedAt'];
const DEFAULT_ADMIN_SHEET_ID = '1upKC-iNWs7HIeKiVVAegve5O5WbNebbjMlveMcvnuow';

function getSheetsCredentials() {
  const keyPath = process.env.GOOGLE_SERVICE_ACCOUNT_KEY_PATH;
  const keyJson = process.env.GOOGLE_SERVICE_ACCOUNT_JSON;

  if (keyPath) {
    try {
      const resolved = join(__dirnameHere, '..', '..', keyPath.replace(/^\.\//, ''));
      return JSON.parse(readFileSync(resolved, 'utf8'));
    } catch (e) {
      console.error('Sheets: failed to read key file', e.message);
      return null;
    }
  }

  if (keyJson) {
    try {
      const raw = keyJson.startsWith('{') ? keyJson : Buffer.from(keyJson, 'base64').toString('utf8');
      return JSON.parse(raw);
    } catch (e) {
      console.error('Sheets: failed to parse GOOGLE_SERVICE_ACCOUNT_JSON', e.message);
      return null;
    }
  }

  return null;
}

function getSheetsAuth() {
  const credentials = getSheetsCredentials();
  if (!credentials) return null;
  return new google.auth.GoogleAuth({
    credentials,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });
}

function getAdminSheetId() {
  return process.env.GOOGLE_ADMIN_SHEET_ID || DEFAULT_ADMIN_SHEET_ID;
}

function normalizeHeader(value) {
  return String(value || '').trim().toLowerCase().replace(/[\s_-]+/g, '');
}

function normalizeName(value) {
  return String(value || '').trim().replace(/\s+/g, ' ');
}

function findHeaderIndex(headers, names) {
  const wanted = new Set(names.map(normalizeHeader));
  return headers.findIndex((value) => wanted.has(normalizeHeader(value)));
}

function getSheetsClient() {
  const auth = getSheetsAuth();
  if (!auth) throw new Error('Google Sheets service account is not configured');
  return google.sheets({ version: 'v4', auth });
}

/** Read the generated MonthlySchedule cache. */
export async function fetchMonthlyScheduleFromSheet() {
  try {
    const sheets = getSheetsClient();
    const res = await sheets.spreadsheets.values.get({
      spreadsheetId: getAdminSheetId(),
      range: MONTHLY_SCHEDULE_RANGE,
    });

    const rows = res.data.values || [];
    if (rows.length < 2) return [];

    const headers = rows[0] || [];
    const idx = {
      eventID: findHeaderIndex(headers, ['eventID']),
      title: findHeaderIndex(headers, ['title']),
      date: findHeaderIndex(headers, ['date']),
      start: findHeaderIndex(headers, ['start']),
      end: findHeaderIndex(headers, ['end']),
      status: findHeaderIndex(headers, ['status']),
      studentName: findHeaderIndex(headers, ['studentName']),
      isKidsLesson: findHeaderIndex(headers, ['isKidsLesson']),
      teacherName: findHeaderIndex(headers, ['teacherName']),
      lessonKind: findHeaderIndex(headers, ['lessonKind']),
    };

    if (idx.eventID < 0 || idx.studentName < 0) return [];

    const lessonKindValid = { regular: true, demo: true, owner: true };
    const out = [];

    for (let i = 1; i < rows.length; i += 1) {
      const row = rows[i] || [];
      const get = (key) => (
        idx[key] >= 0 && row[idx[key]] != null
          ? String(row[idx[key]]).trim()
          : ''
      );
      const eventID = get('eventID');
      const studentName = get('studentName');
      if (!eventID || !studentName) continue;

      const rawKind = get('lessonKind').toLowerCase();
      const lessonKind = lessonKindValid[rawKind] ? rawKind : 'regular';
      const kidsRaw = get('isKidsLesson');

      out.push({
        sheetRow: i + 1,
        eventID,
        title: get('title'),
        date: get('date'),
        start: get('start'),
        end: get('end'),
        status: get('status') || 'scheduled',
        studentName,
        isKidsLesson: kidsRaw === '子' || kidsRaw === 'true' || row[idx.isKidsLesson] === true,
        teacherName: get('teacherName'),
        lessonKind,
      });
    }

    return out;
  } catch (err) {
    console.error('[sheets] MonthlySchedule fetch error:', err.message);
    return [];
  }
}

async function spreadsheetHasSheet(sheets, title) {
  const meta = await sheets.spreadsheets.get({
    spreadsheetId: getAdminSheetId(),
    fields: 'sheets.properties.title',
  });
  return (meta.data.sheets || []).some((sheet) => sheet?.properties?.title === title);
}

/**
 * Create/validate the persistent CalendarStudentIDs tab.
 * Rewriting the same header row also acts as a harmless write-permission preflight
 * before we touch Google Calendar.
 */
export async function prepareCalendarStudentIdSheet() {
  const sheets = getSheetsClient();
  const spreadsheetId = getAdminSheetId();
  const exists = await spreadsheetHasSheet(sheets, STUDENT_ID_SHEET);

  if (!exists) {
    await sheets.spreadsheets.batchUpdate({
      spreadsheetId,
      requestBody: {
        requests: [{ addSheet: { properties: { title: STUDENT_ID_SHEET } } }],
      },
    });
  }

  await sheets.spreadsheets.values.update({
    spreadsheetId,
    range: `'${STUDENT_ID_SHEET}'!A1:E1`,
    valueInputOption: 'RAW',
    requestBody: { values: [STUDENT_ID_HEADERS] },
  });

  return { ok: true, created: !exists };
}

/** Read persistent student-number tag state. Missing tab means no IDs are cached yet. */
export async function fetchCalendarStudentIdsFromSheet() {
  try {
    const sheets = getSheetsClient();
    const exists = await spreadsheetHasSheet(sheets, STUDENT_ID_SHEET);
    if (!exists) return [];

    const res = await sheets.spreadsheets.values.get({
      spreadsheetId: getAdminSheetId(),
      range: `'${STUDENT_ID_SHEET}'!A:E`,
    });
    const rows = res.data.values || [];
    if (rows.length < 2) return [];

    const headers = rows[0] || [];
    const idx = {
      eventID: findHeaderIndex(headers, ['eventID']),
      date: findHeaderIndex(headers, ['date']),
      studentName: findHeaderIndex(headers, ['studentName']),
      studentID: findHeaderIndex(headers, ['studentID', 'student_id']),
      updatedAt: findHeaderIndex(headers, ['updatedAt']),
    };
    if (idx.eventID < 0 || idx.date < 0 || idx.studentName < 0 || idx.studentID < 0) return [];

    const out = [];
    for (let i = 1; i < rows.length; i += 1) {
      const row = rows[i] || [];
      const get = (key) => (
        idx[key] >= 0 && row[idx[key]] != null
          ? String(row[idx[key]]).trim()
          : ''
      );
      const eventID = get('eventID');
      const date = get('date');
      const studentName = get('studentName');
      const studentID = get('studentID');
      if (!eventID || !date || !studentName || !studentID) continue;
      out.push({
        sheetRow: i + 1,
        eventID,
        date,
        studentName,
        studentID,
        updatedAt: get('updatedAt'),
      });
    }
    return out;
  } catch (err) {
    console.error('[sheets] CalendarStudentIDs fetch error:', err.message);
    return [];
  }
}

function cacheKey(eventID, date, studentName) {
  return `${String(eventID || '').trim()}\t${String(date || '').trim()}\t${normalizeName(studentName)}`;
}

/**
 * Persist verified Calendar tag state.
 * assignments: [{ eventID, date, studentName, studentID }]
 */
export async function writeCalendarStudentIds(assignments) {
  const requested = Array.isArray(assignments) ? assignments : [];
  if (requested.length === 0) return { ok: true, inserted: 0, updated: 0, alreadyPresent: 0 };

  await prepareCalendarStudentIdSheet();
  const sheets = getSheetsClient();
  const spreadsheetId = getAdminSheetId();
  const existing = await fetchCalendarStudentIdsFromSheet();
  const byKey = new Map();

  for (const row of existing) {
    const key = cacheKey(row.eventID, row.date, row.studentName);
    if (!byKey.has(key)) byKey.set(key, []);
    byKey.get(key).push(row);
  }

  const updates = [];
  const appends = [];
  let alreadyPresent = 0;
  const now = new Date().toISOString();

  for (const assignment of requested) {
    const eventID = String(assignment.eventID || '').trim();
    const date = String(assignment.date || '').trim();
    const studentName = normalizeName(assignment.studentName);
    const studentID = String(assignment.studentID || '').trim();
    if (!eventID || !date || !studentName || !studentID) {
      throw new Error('Invalid CalendarStudentIDs assignment');
    }

    const matches = byKey.get(cacheKey(eventID, date, studentName)) || [];
    if (matches.length > 1) {
      throw new Error(`CalendarStudentIDs has duplicate rows for ${studentName} on ${date}`);
    }

    if (matches.length === 1) {
      const current = String(matches[0].studentID || '').trim();
      if (current && current !== studentID) {
        throw new Error(
          `CalendarStudentIDs already has studentID ${current} for ${studentName}; refusing ${studentID}`
        );
      }
      if (current === studentID) {
        alreadyPresent += 1;
        continue;
      }
      updates.push({
        range: `'${STUDENT_ID_SHEET}'!D${matches[0].sheetRow}:E${matches[0].sheetRow}`,
        values: [[studentID, now]],
      });
      continue;
    }

    appends.push([eventID, date, studentName, studentID, now]);
  }

  if (updates.length > 0) {
    await sheets.spreadsheets.values.batchUpdate({
      spreadsheetId,
      requestBody: { valueInputOption: 'RAW', data: updates },
    });
  }

  if (appends.length > 0) {
    await sheets.spreadsheets.values.append({
      spreadsheetId,
      range: `'${STUDENT_ID_SHEET}'!A:E`,
      valueInputOption: 'RAW',
      insertDataOption: 'INSERT_ROWS',
      requestBody: { values: appends },
    });
  }

  return {
    ok: true,
    inserted: appends.length,
    updated: updates.length,
    alreadyPresent,
  };
}

export function isSheetsConfigured() {
  return !!(
    getSheetsAuth() &&
    (process.env.GOOGLE_ADMIN_SHEET_ID || process.env.GOOGLE_SERVICE_ACCOUNT_KEY_PATH || process.env.GOOGLE_SERVICE_ACCOUNT_JSON)
  );
}
